# Generated by Django 4.0.3 on 2022-03-05 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Anon', max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(default='Anonov', max_length=25, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=15, verbose_name='Пол')),
                ('avatar', models.ImageField(default='images/default_avatar.jpg', upload_to='images/avatars/')),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ManyToManyField(to='api_backend.participant', verbose_name='Участник')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
