# Generated by Django 4.0.3 on 2022-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние'),
        ),
    ]
