# Generated by Django 4.0.2 on 2022-02-13 19:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0002_remove_participant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
