# Generated by Django 4.0.2 on 2022-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0003_alter_participant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(default='images/avatars/default-avatar.jpg', upload_to='images/avatars/'),
        ),
    ]
