# Generated by Django 4.0.2 on 2022-02-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0014_alter_participantmatch_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='Anon', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='Anonov', max_length=25),
        ),
    ]
