# Generated by Django 4.0.2 on 2022-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0015_participant_email_participant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='participant',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='Anon', max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='Anonov', max_length=25, verbose_name='Фамилия'),
        ),
    ]
