# Generated by Django 4.0.2 on 2022-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0017_remove_participantmatch_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmatch',
            name='participant',
            field=models.ManyToManyField(to='api_backend.Participant', verbose_name='Участник'),
        ),
    ]
