# Generated by Django 4.0.2 on 2022-02-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0018_alter_participantmatch_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='match',
            field=models.ManyToManyField(to='api_backend.Participant'),
        ),
        migrations.DeleteModel(
            name='ParticipantMatch',
        ),
    ]
