# Generated by Django 4.0.2 on 2022-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0019_participant_match_delete_participantmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='match',
            field=models.ManyToManyField(blank=True, to='api_backend.Participant'),
        ),
    ]
