# Generated by Django 4.0.2 on 2022-02-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0021_participant_match_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='match_updated',
        ),
    ]
