# Generated by Django 4.0.2 on 2022-02-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_backend', '0022_remove_participant_match_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='match',
        ),
        migrations.CreateModel(
            name='ParticipantMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ManyToManyField(to='api_backend.Participant', verbose_name='Участник')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
