# Generated by Django 4.0.2 on 2022-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0023_remove_participant_match_participantmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
