# Generated by Django 4.0.2 on 2022-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0024_participantmatch_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantmatch',
            name='updated_at',
        ),
    ]
